"""
eda.py — MixedWM38 exploratory analysis. Writes docs/DATA.md + assets/ figures.

Run after scripts/download_data.py:

    python scripts/eda.py

Everything in DATA.md is computed from the local file at run time, so the
document doubles as a verification record of the dataset facts.
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from wafer_mixed.config import MixedConfig, REPO_ROOT
from wafer_mixed.data import LABEL_NAMES, combo_name, load_raw, load_splits

ASSETS = REPO_ROOT / "assets"
DOCS = REPO_ROOT / "docs"
_RNG = np.random.default_rng(0)


def _sample_grid(maps: np.ndarray, groups: list[tuple[str, np.ndarray]],
                 out_path: Path, n_cols: int = 4) -> None:
    """One row of n_cols example maps per (name, indices) group."""
    n_rows = len(groups)
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(2.2 * n_cols, 2.4 * n_rows))
    axes = np.atleast_2d(axes)
    for r, (name, idxs) in enumerate(groups):
        pick = _RNG.choice(idxs, size=min(n_cols, len(idxs)), replace=False)
        for c in range(n_cols):
            ax = axes[r, c]
            ax.set_axis_off()
            if c < len(pick):
                ax.imshow(maps[pick[c]], cmap="viridis", vmin=0, vmax=2)
            if c == 0:
                ax.set_title(name, loc="left", fontsize=10)
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=80, bbox_inches="tight")
    plt.close(fig)
    print(f"wrote {out_path}")


def main() -> None:
    cfg = MixedConfig.from_yaml(REPO_ROOT / "configs" / "baseline.yaml")
    maps, labels = load_raw(cfg.data_root)
    n = len(maps)
    n_active = labels.sum(axis=1)

    # --- figures -----------------------------------------------------------
    single_groups = [("normal", np.where(n_active == 0)[0])] + [
        (LABEL_NAMES[k], np.where((labels[:, k] == 1) & (n_active == 1))[0])
        for k in range(len(LABEL_NAMES))
    ]
    _sample_grid(maps, single_groups, ASSETS / "singles_grid.png")

    combos, inverse, counts = np.unique(
        labels, axis=0, return_inverse=True, return_counts=True
    )
    combo_rows = sorted(
        range(len(combos)), key=lambda i: (combos[i].sum(), combo_name(combos[i]))
    )
    for k_mix in (2, 3, 4):
        groups = [
            (combo_name(combos[i]), np.where(inverse == i)[0])
            for i in combo_rows if combos[i].sum() == k_mix
        ]
        _sample_grid(maps, groups, ASSETS / f"mixed{k_mix}_grid.png")

    # --- tables ------------------------------------------------------------
    per_label = [
        f"| {k} | {LABEL_NAMES[k]} | {int(labels[:, k].sum()):,} | "
        f"{int(((labels[:, k] == 1) & (n_active == 1)).sum()):,} | "
        f"{int(((labels[:, k] == 1) & (n_active > 1)).sum()):,} |"
        for k in range(len(LABEL_NAMES))
    ]

    combo_table = [
        f"| {combo_name(combos[i])} | {int(combos[i].sum())} | {counts[i]:,} |"
        for i in combo_rows
    ]

    mix_hist = np.bincount(n_active.astype(int), minlength=5)
    n_stray = int((maps > 2).sum())
    n_stray_maps = int(((maps > 2).any(axis=(1, 2))).sum())

    # --- split summary -----------------------------------------------------
    split_section = ""
    try:
        splits = load_splits(cfg)
        combo_cover = all(
            len(np.unique(inverse[idx])) == len(combos)
            for idx in splits.values()
        )
        split_section = (
            f"| Split | Maps |\n|---|---|\n"
            f"| train | {len(splits['train']):,} |\n"
            f"| val | {len(splits['val']):,} |\n"
            f"| test | {len(splits['test']):,} |\n\n"
            f"All 38 combinations present in every split: **{combo_cover}**.\n"
            f"Indices persisted in `data/splits.npz` (seed {cfg.seed}); regenerated\n"
            f"only if that file is deleted.\n"
        )
    except FileNotFoundError:
        split_section = "_Splits not yet generated — run scripts/download_data.py._\n"

    md = f"""# MixedWM38 — dataset notes (generated by scripts/eda.py)

Source: [Junliangwangdhu/WaferMap](https://github.com/Junliangwangdhu/WaferMap)
(Wang et al. 2020, IEEE TSM, doi:10.1109/TSM.2020.3020985). Mirrors: Kaggle
(`co1d7era/mixedtype-wafer-defect-datasets`), Google Drive (authors' link).
Public dataset — no proprietary or employer data is used anywhere in this repo.

## Verified facts (computed from the local copy)

- **{n:,} wafer maps**, 52×52, stored as `arr_0` (int32) in `MixedWM38.npz`.
- Labels `arr_1`: (**{n:,}, 8) multi-hot** over 8 basic defect types; all-zero
  row = normal wafer. **38 unique combinations** (1 normal + 8 single +
  13 two-mix + 12 three-mix + 4 four-mix).
- Pixel semantics: 0 = outside wafer, 1 = passing die, 2 = failing die —
  same as WM-811K.
- **Deviation from upstream docs:** {n_stray} pixels across {n_stray_maps} maps
  carry the undocumented value 3. `encode_map` clips to [0, 2], so they are
  treated as failing die.
- Upstream states the mixed patterns were partially **GAN-generated** to
  balance combination counts (most combos have exactly 1,000 maps). The two
  irregular counts — Near-full single ({int(((labels[:, 5] == 1) & (n_active == 1)).sum())})
  and Random single ({int(((labels[:, 7] == 1) & (n_active == 1)).sum())}) — echo the
  natural scarcities in WM-811K. Random never appears in any mix.

### Label ordering (verified visually — undocumented upstream)

Upstream README only says the 8 columns are basic types "C2–C9" without
naming the order. The ordering below was confirmed by rendering single-type
samples per column (`assets/singles_grid.png`) and matching the canonical
pattern morphologies:

| Column | Label | Total maps | As single | In mixes |
|---|---|---|---|---|
""" + "\n".join(per_label) + f"""

## Labels-per-map distribution

| # active labels | 0 (normal) | 1 | 2 | 3 | 4 |
|---|---|---|---|---|---|
| maps | {mix_hist[0]:,} | {mix_hist[1]:,} | {mix_hist[2]:,} | {mix_hist[3]:,} | {mix_hist[4]:,} |

## Combination frequency (all 38 types)

| Combination | # labels | Maps |
|---|---|---|
""" + "\n".join(combo_table) + f"""

## Sample grids

- Singles + normal: ![singles](../assets/singles_grid.png)
- Two-mix: ![mixed2](../assets/mixed2_grid.png)
- Three-mix: ![mixed3](../assets/mixed3_grid.png)
- Four-mix: ![mixed4](../assets/mixed4_grid.png)

## Train/val/test split

Stratified by the full 38-type combination (fixed seed), so every rare mix
appears in all three splits.

""" + split_section

    DOCS.mkdir(parents=True, exist_ok=True)
    out = DOCS / "DATA.md"
    out.write_text(md)
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
